Web Applications/Budgetary App Final Edition/Models/Bills.cs
namespace Budgetary_App_Final_Edition.Models
{
    public class Bills
    {

        public int id { get; set; }

        public string name { get; set; }
        public double amount { get; set; }
        public int modeofPayment { get; set; }
        
        public string category { get; set; }
        public double startingBudget { get; set; }
        public double dailyBudget { get; set; }

        public DateTime date { get; set; }

		public Bills()
        {
        }
    }
}

Web Applications/Budgetary App Final Edition/Controllers/BillsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Budgetary_App_Final_Edition.Data;
using Budgetary_App_Final_Edition.Models;
using Microsoft.AspNetCore.Authorization;
using SQLitePCL;
using System.Runtime.ExceptionServices;

namespace Budgetary_App_Final_Edition.Controllers
{
	public class BillsController : Controller
	{
		private readonly ApplicationDbContext _context;

		public BillsController(ApplicationDbContext context)
		{
			_context = context;
		}

		[Authorize]
		// GET: Bills
		public async Task<IActionResult> Dashboard()
		{
			return View(await _context.Bills.ToListAsync());
		}

		[Authorize]
		// GET: Bills/Details/5
		public async Task<IActionResult> Details(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var bills = await _context.Bills
				.FirstOrDefaultAsync(m => m.id == id);
			if (bills == null)
			{
				return NotFound();
			}

			return View(bills);
		}
		[Authorize]
		// GET: Bills/Create
		public IActionResult Create()
		{
			var lastBill = _context.Bills.OrderByDescending(b => b.id).FirstOrDefault();
			var startingBudget = 0.00;
			var dailyBudget = 0.00;
			var modeOfPayment = 0;

			if (lastBill != null)
			{
				startingBudget = lastBill.startingBudget;
				dailyBudget = lastBill.dailyBudget;
				modeOfPayment = lastBill.modeofPayment;

			}

			var bill = new Bills
			{
				startingBudget = startingBudget,
				dailyBudget = dailyBudget,
				modeofPayment = modeOfPayment

			};

			ViewBag.ModeOfPayment = modeOfPayment;

			return View(bill);
		}

		[Authorize]
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create([Bind("id,name,amount,modeofPayment,category,startingBudget,dailyBudget")] Bills bills)
		{
			if (ModelState.IsValid)
			{
				bills.date = DateTime.Today;

				_context.Add(bills);
				await _context.SaveChangesAsync();
				return RedirectToAction(nameof(Dashboard));

			}
			else
			{
				// Log the validation errors
				var errors = ModelState.Values.SelectMany(v => v.Errors);
				foreach (var error in errors)
				{
					Console.WriteLine(error.ErrorMessage);
				}
			}
			return View(bills);

		}

		[Authorize]
		private bool BillsExists(int id)
		{
			return _context.Bills.Any(e => e.id == id);
		}

		[Authorize]
		[HttpPost("Bills/Edit/{id}")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> BillsEdit(int id, [Bind("id,name,amount,category")] Bills bills)
		{
			if (id != bills.id)
			{
				return NotFound();
			}

			if (ModelState.IsValid)
			{
				try
				{
					// Retrieve the existing bill from the database
					var existingBill = await _context.Bills.FindAsync(id);
					if (existingBill == null)
					{
						return NotFound();
					}

					// Update only the necessary fields
					existingBill.name = bills.name;
					existingBill.amount = bills.amount;
					existingBill.category = bills.category;

					// Save the changes
					await _context.SaveChangesAsync();
				}
				catch (DbUpdateConcurrencyException)
				{
					if (!BillsExists(bills.id))
					{
						return NotFound();
					}
					else
					{
						throw;
					}
				}
				return RedirectToAction(nameof(Dashboard));
			}

			// Log the validation errors
			var errors = ModelState.Values.SelectMany(v => v.Errors);
			foreach (var error in errors)
			{
				Console.WriteLine(error.ErrorMessage);
			}

			return View(bills);
		}

		[Authorize]
		[HttpGet("Bills/Edit/{id}")]
		// GET: Bills/Edit/5
		public async Task<IActionResult> BillsEdit(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var bills = await _context.Bills.FindAsync(id);
			if (bills == null)
			{
				return NotFound();
			}
			return View(bills);
		}

		[Authorize]
		// POST: Bills/Delete/5
		[HttpPost, ActionName("BillsDelete")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> BillsDelete(int id)
		{
			var bills = await _context.Bills.FindAsync(id);
			if (bills != null)
			{
				_context.Bills.Remove(bills);
			}

			await _context.SaveChangesAsync();
			return RedirectToAction(nameof(Dashboard));
		}

		[Authorize]
		// GET: Bills/Delete/5
		public async Task<IActionResult> BillsDelete(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var bills = await _context.Bills
				.FirstOrDefaultAsync(m => m.id == id);
			if (bills == null)
			{
				return NotFound();
			}

			return View(bills);
		}


		[HttpGet]
		public IActionResult GetMonthlyExpensesLine()
		{
			var expenses = _context.Bills
								   .GroupBy(b => b.date.Month)
								   .Select(g => new
								   {
									   Month = g.Key,
									   TotalExpenses = g.Sum(b => b.amount),							
								   })
								   .ToList();

			// Get the oldest date recorded in the current month
			var currentDate = DateTime.Now;
			var currentMonth = DateTime.Now.Month;
			var currentYear = DateTime.Now.Year;
			var oldestDateThisMonth = _context.Bills
											  .Where(b => b.date.Month == currentMonth && b.date.Year == currentYear)
											  .OrderBy(b => b.date)
											  .Select(b => b.date)
											  .FirstOrDefault();

			if (oldestDateThisMonth == default)
			{
				oldestDateThisMonth = currentDate;
			}

			var lastBill = _context.Bills
									.Where(b => b.date.Month == currentMonth && b.date.Year == currentYear)
									.OrderByDescending(b => b.date)
									.FirstOrDefault();

			var lastDayOfMonth = new DateTime(currentYear, currentMonth, DateTime.DaysInMonth(currentYear, currentMonth));
			var daysLeft = (lastDayOfMonth - oldestDateThisMonth).Days;


			var monthNames = expenses.Select(e => new DateTime(1, e.Month, 1).ToString("MMMM")).ToList();
			var dailyBudget = lastBill?.dailyBudget ?? 0.0;

			var expensesData = expenses.Select(e => e.TotalExpenses + (dailyBudget * daysLeft)).ToList();

			var startingBudget = lastBill?.startingBudget ?? 0.0;
			if (startingBudget == 0.0 || dailyBudget == 0.0)
			{
				var lastBudgetLastMonth = _context.Bills
					.Where(b => b.date < new DateTime(currentYear, currentMonth, 1))
					.OrderByDescending(b => b.date)
					.FirstOrDefault();

				startingBudget = lastBudgetLastMonth?.startingBudget ?? 0.0;
				dailyBudget = lastBudgetLastMonth?.dailyBudget ?? 0.0;

				// Calculate daysLeft based on last month's first and last entries
				var oldestDateLastMonth = _context.Bills
					.Where(b => b.date.Month == lastBudgetLastMonth.date.Month && b.date.Year == lastBudgetLastMonth.date.Year)
					.OrderBy(b => b.date)
					.Select(b => b.date)
					.FirstOrDefault();

				var newestDateLastMonth = _context.Bills
					.Where(b => b.date.Month == lastBudgetLastMonth.date.Month && b.date.Year == lastBudgetLastMonth.date.Year)
					.OrderByDescending(b => b.date)
					.Select(b => b.date)
					.FirstOrDefault();

				daysLeft = (newestDateLastMonth - oldestDateLastMonth).Days;

			}
			var totalExpense = expensesData.Sum();
			var actualDaysLeft = (lastDayOfMonth - currentDate).Days + 1;

			var totalBudgetAfterExpenses = new List<double>();
			foreach (var expense in expenses)
			{
				var monthlyBudget = startingBudget - (dailyBudget * daysLeft) - expense.TotalExpenses;

				totalBudgetAfterExpenses.Add(monthlyBudget);
			}

			var averageExpenses = totalExpense / monthNames.Count;
			var averageSavings = totalBudgetAfterExpenses.Average();

			if (averageSavings < 0)
			{
				var lastRecordLastMonth = _context.Bills
					.Where(b => b.date < new DateTime(currentYear, currentMonth, 1))
					.OrderByDescending(b => b.date)
					.FirstOrDefault();

				averageSavings = lastRecordLastMonth?.startingBudget ?? 0.0;
			}

			/*if (averageSavings < 0)
			{
				averageSavings = 0;
			}*/

			//Console.WriteLine(averageExpenses);
			//Console.WriteLine(totalExpense);
			//Console.WriteLine(monthNames.Count);
			Console.WriteLine(totalExpense);



			return Json(new { monthNames, expensesData, totalExpense, startingBudget, dailyBudget, oldestDateThisMonth, actualDaysLeft, totalBudgetAfterExpenses, averageExpenses, averageSavings });
		}

		[HttpGet]
		public IActionResult GetMonthlyExpensesPie()
		{
			var expenses = _context.Bills
								   .GroupBy(b => new { b.date.Month, b.category })
								   .Select(g => new
								   {
									   TotalExpenses = g.Sum(b => b.amount),
									   Category = g.Key.category
								   })
								   .ToList();

			var expenseCategories = expenses.Select(e => e.Category).Distinct().ToList();
			var expensesData = expenses.Select(e => e.TotalExpenses).ToList();

			var categoryMap = new Dictionary<string, string>
			{
				{ "1", "Food" },
				{ "2", "Transportation" },
				{ "3", "Utilities" },
				{ "4", "Others" }
			};

			for (int i = 0; i < expenseCategories.Count; i++)
			{
				if (categoryMap.ContainsKey(expenseCategories[i]))
				{
					expenseCategories[i] = categoryMap[expenseCategories[i]];
				}
			}

			return Json(new { expensesData, expenseCategories });
		}


		[HttpGet]
		public IActionResult GetPastThreeMonthsSavings()
		{
			var currentMonth = DateTime.Now.Month;
			var currentYear = DateTime.Now.Year;

			// Calculate start date as three months ago from the current month
			var startDate = DateTime.Now.AddMonths(-2);
			var endDate = new DateTime(currentYear, currentMonth, DateTime.DaysInMonth(currentYear, currentMonth));
			var monthNames = new List<string>();

			// Get bills for the last three months
			var billsLastThreeMonths = _context.Bills
				.Where(b => b.date >= startDate && b.date <= endDate)
				.OrderBy(b => b.date)
				.ToList();

			var totalBudgetAfterExpenses = new List<double>();

			for (int i = 0; i < 3; i++)
			{
				var monthToCalculate = startDate.AddMonths(i).Month;
				var yearToCalculate = startDate.AddMonths(i).Year;
				var daysInMonth = DateTime.DaysInMonth(yearToCalculate, monthToCalculate);

				// Filter bills for the current month being calculated

Web Applications/Budgetary App Final Edition/Views/Bills/BillsDelete.cshtml
@model Budgetary_App_Final_Edition.Models.Bills

@{
    ViewData["Title"] = "Delete";
}

<div class="container-fluid" style="width: 40%;">
        <div class="row">
            <div class="col">
                <section class="position-relative py-4 py-xl-5">
                    <div class="container position-relative">
                        <div class="row d-flex justify-content-center">
                            <div class="col-1 col-md-8 col-lg-6 col-xl-5 col-xxl-12">
                                <div class="row d-flex justify-content-center">
                                    <div class="col">
                                        <div class="card mb-5">
                                        <form asp-action="BillsDelete">
                                            <div class="card-body text-center p-sm-5">
                                                <h2 class="text-center mb-4">Delete Expenses</h2><small>Are you sure you want to delete the following?</small>
                                                <hr>
                                            
                                                <input type="hidden" asp-for="id" />
                                                <div>
                                                    <label class="form-label fs-6 fw-bold text-start" style="width: 100%;">Expenses Name:</label>
                                                    <label class="form-label text-start" style="width: 100%;">@Model.name</label>
                                                    </div>
                                                    <div>
                                                        <label class="form-label fs-6 fw-bold text-start" style="width: 100%;">Category:</label>
                                                        <label class="form-label text-start" style="width: 100%;">@Model.category</label>
                                                        </div>
                                                    <div>
                                                        <label class="form-label fs-6 fw-bold text-start" style="width: 100%;">Amount:</label>
                                                        <label class="form-label text-start" style="width: 100%;">@Model.amount</label>
                                                    </div>
                                                
                                                <hr>
                                                <div>
                                                    <button class="btn btn-primary d-block w-100" type="submit" style="background: var(--bs-secondary-bg);width: 50%;">Submit</button></div>
                                            </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>

Web Applications/Budgetary App Final Edition/Views/Bills/BillsEdit.cshtml
@model Budgetary_App_Final_Edition.Models.Bills

@{
	ViewData["Title"] = "Edit";
}
<div class="container-fluid" style="width: 40%;">
	<div class="row">
		<div class="col">
			<section class="position-relative py-4 py-xl-5">
				<div class="container position-relative">
					<div class="row d-flex justify-content-center">
						<div class="col-1 col-md-8 col-lg-6 col-xl-5 col-xxl-12">
							<div class="row d-flex justify-content-center">
								<div class="col">
									<div class="card mb-5">
										<div class="card-body p-sm-5">
											<h2 class="text-center mb-4">Edit Expenses</h2>
											<hr>
											<form asp-action="BillsEdit" method="post">
												<div asp-validation-summary="ModelOnly" class="text-danger"></div>
												<input type="hidden" asp-for="id" />
												<div class="form-floating mb-3">
													<input asp-for="name" id="floatingInput-1" class="form-control form-control" placeholder="Food" />
													<label class="form-label" for="floatingInput">Expenses Name</label>
													<span asp-validation-for="name" class="text-danger"></span>
												</div>
												<div class="form-floating mb-3">
													<input asp-for="amount" id="floatingInput-4" class="form-control form-control" type="number" placeholder="2000" name="amount" />
													<label class="form-label" for="floatingInput">Amount</label></div>
												<span asp-validation-for="amount" class="text-danger"></span>
												<div class="mb-3"></div>
												<div class="mb-3">
													<div class="dropdown">
														<button id="categoryBtn" class="btn btn-primary dropdown-toggle" aria-expanded="false" data-bs-toggle="dropdown" type="button" style="width: 100%;background: var(--bs-secondary-bg);">Categories</button>
														<input asp-for="category" type="hidden" id="category" name="category" />
														<div class="dropdown-menu">
															<a class="dropdown-item" href="#" data-value="1" data-type="category">Food</a>
															<a class="dropdown-item" href="#" data-value="2" data-type="category">Transportation</a>
															<a class="dropdown-item" href="#" data-value="3" data-type="category">Utility</a>
															<a class="dropdown-item" href="#" data-value="4" data-type="category">Others</a>
														</div>
													</div>
													<script>
														if ($("#category").val() == 1) {
															$("#categoryBtn").text("Food");
														}
														else if ($("#category").val() == 2) {
															$("#categoryBtn").text("Transportation");
														}
														else if ($("#category").val() == 3) {
															$("#categoryBtn").text("Utility");
														}
														else if ($("#category").val() == 4) {
															$("#categoryBtn").text("Others");
														}
													</script>
												</div>
												<hr>
												<div>
													<div class="btn-group" role="group" style="width: 100%;">
														<a class="btn btn-primary d-block w-100" role="button" style="background:var(--bs-secondary-bg);" asp-controller="Bills" asp-action="Dashboard">Go back to list</a>
														<button class="btn btn-primary d-block w-100" type="submit" style="background:var(--bs-secondary-bg);">Submit</button>
													</div>
												</div>
											</form>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</section>
		</div>
	</div>
</div>

Web Applications/Budgetary App Final Edition/Views/Bills/Dashboard.cshtml
@model IEnumerable<Budgetary_App_Final_Edition.Models.Bills>

@{
	ViewData["Title"] = "Index";
}


<div class="container-fluid" style="height: 321%;">
	<div class="d-sm-flex justify-content-between align-items-center mb-4">
		<h3 class="text-dark mb-0"></h3>
	</div>
	<div class="row">
		<div class="col-md-6 col-xl-3 mb-4">
			<div class="card shadow border-left-primary py-2" style="background: var(--bs-body-color);">
				<div class="card-body">
					<div class="row g-0 align-items-center">
						<div class="col me-2">
							<div class="text-uppercase text-primary fw-bold text-xs mb-1"><span style="color: var(--bs-body-bg);--bs-body-font-size: -1rem;">average SAVINGS (MONTHLY)</span></div>
							<div class="text-dark fw-bold h5 mb-0">&#x20B1;<span id="averageSavings"></span></div>
						</div>
						<div class="col-auto"><i class="fas fa-calendar fa-2x text-gray-300"></i></div>
					</div>
				</div>
			</div>
		</div>
		<div class="col-md-6 col-xl-3 mb-4">
			<div class="card shadow border-left-success py-2" style="background: var(--bs-body-color);">
				<div class="card-body">
					<div class="row g-0 align-items-center">
						<div class="col me-2">
							<div class="text-uppercase text-success fw-bold text-xs mb-1"><span style="color: var(--bs-body-bg);">Average EXPENSES (MONTHLY)</span></div>
							<div class="text-dark fw-bold h5 mb-0">&#x20B1;<span id="averageExpenses"></span></div>
						</div>
						<div class="col-auto"><i class="fas fa-dollar-sign fa-2x text-gray-300"></i></div>
					</div>
				</div>
			</div>
		</div>
		<div class="col-md-6 col-xl-3 mb-4">
			<div class="card shadow border-left-info py-2" style="background: var(--bs-body-color);">
				<div class="card-body">
					<div class="row g-0 align-items-center">
						<div class="col me-2">
							<div class="text-uppercase text-info fw-bold text-xs mb-1"><span style="color: var(--bs-body-bg);">SAVINGS:EXPENSES</span></div>
							<div class="row g-0 align-items-center">
								<div class="col-auto">
									<div class="text-dark fw-bold h5 mb-0 me-3"><span id="savingsToRatio"></span></div>
								</div>
								<div class="col">
									<div class="progress bg-body progress-sm" data-bs-theme="dark" style="color: var(--bs-progress-bar-color);background: var(--bs-progress-bar-color);border-color: var(--bs-progress-bar-color);">
										<div id="ratioProgress" class="progress-bar bg-light" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100" style="width: 50%;"><span class="visually-hidden"></span></div>
									</div>
								</div>
							</div>
						</div>
						<div class="col-auto"><i class="fas fa-clipboard-list fa-2x text-gray-300"></i></div>
					</div>
				</div>
			</div>
		</div>
		<div class="col-md-6 col-xl-3 mb-4">
			<div class="card shadow border-left-warning py-2" style="background: var(--bs-body-color);">
				<div class="card-body">
					<div class="row g-0 align-items-center">
						<div class="col me-2">
							<div class="text-uppercase text-warning fw-bold text-xs mb-1"><span style="color: var(--bs-body-bg);">DAYS BEFORE NEXT CUTOFF</span></div>
							<div class="text-dark fw-bold h5 mb-0"><span id="daysLeft" ></span></div>
						</div>
						<div class="col-auto"><i class="fas fa-comments fa-2x text-gray-300"></i></div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-lg-7 col-xl-8">
			<div class="card shadow mb-4" style="height: 278.188px;">
				<div class="card-header d-flex justify-content-between align-items-center" style="background:var(--bs-body-color);">
					<h6 class="fw-bold" style="color: var(--bs-body-bg);margin-bottom: 5px;margin-top: 5px;">Expenses Overview</h6>
				</div>

				@* Expenses Overview Chart *@
				<div class="card-body">
					<div class="chart-area" style="filter: invert(0%); color: var(--bs-body-color); height: 197px;">
						<canvas id="ExpensesOverviewChart"></canvas>
					</div>
				</div>
			</div>
		</div>
		<div class="col-lg-5 col-xl-4">
			<div class="card shadow mb-4">
				<div class="card-header d-flex justify-content-between align-items-center" style="background: var(--bs-body-color);">
					<h6 class="fw-bold" style="color: var(--bs-body-bg);">Expenses Sources</h6>
				</div>

				@* Expenses Sources Chart *@
				<div class="card-body">
					<div class="chart-area">
						<canvas id="expSrcsChrt"</canvas>
					</div>
					<div class="text-center small mt-4" id="chartLegend"></div>
				</div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-lg-7 col-xl-8">
			<div class="card shadow mb-4" style="height: 278.188px;">
				<div class="card-header d-flex justify-content-between align-items-center" style="background:var(--bs-body-color);">
					<h6 class="fw-bold" style="color: var(--bs-body-bg);margin-bottom: 5px;margin-top: 5px;">Actual Savings Overview</h6>
				</div>

				@* Savings Overview *@
				<div class="card-body">
					<div class="chart-area" style="filter: invert(0%);color: var(--bs-body-color);height: 197px;">
						<canvas id="svngOverview"></canvas>
					</div>
				</div>
			</div>
		</div>
		<div class="col-lg-5 col-xl-4">
			<div class="card shadow mb-4" style="height: 276.188px;">
				<div class="card-header d-flex justify-content-between align-items-center" style="background: var(--bs-body-color);">
					<h6 class="fw-bold" style="color: var(--bs-body-bg);">Predicted Savings based on (last three months)</h6>
				</div>

				@* Savings Chart (last three months) *@
				<div class="card-body">
					<div class="chart-area" style="height: 195px;">
						<canvas id="svngDonutChrt"></canvas>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<partial name="_CreateTableView" />

Web Applications/Budgetary App Final Edition/Views/Bills/Delete.cshtml
@model Budgetary_App_Final_Edition.Models.Bills

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Bills</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.amount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.amount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.modeofPayment)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.modeofPayment)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.startingBudget)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.startingBudget)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.dailyBudget)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.dailyBudget)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Web Applications/Budgetary App Final Edition/Views/Bills/Details.cshtml
@model Budgetary_App_Final_Edition.Models.Bills

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Bills</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.amount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.amount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.modeofPayment)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.modeofPayment)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.startingBudget)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.startingBudget)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.dailyBudget)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.dailyBudget)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Web Applications/Budgetary App Final Edition/Views/Bills/Edit.cshtml
@model Budgetary_App_Final_Edition.Models.Bills

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Bills</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="id" />
            <div class="form-group">
                <label asp-for="name" class="control-label"></label>
                <input asp-for="name" class="form-control" />
                <span asp-validation-for="name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="amount" class="control-label"></label>
                <input asp-for="amount" class="form-control" />
                <span asp-validation-for="amount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="modeofPayment" class="control-label"></label>
                <input asp-for="modeofPayment" class="form-control" />
                <span asp-validation-for="modeofPayment" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="category" class="control-label"></label>
                <input asp-for="category" class="form-control" />
                <span asp-validation-for="category" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="startingBudget" class="control-label"></label>
                <input asp-for="startingBudget" class="form-control" />
                <span asp-validation-for="startingBudget" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="dailyBudget" class="control-label"></label>
                <input asp-for="dailyBudget" class="form-control" />
                <span asp-validation-for="dailyBudget" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Dashboard">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Web Applications/Budgetary App Final Edition/Views/Bills/Index.cshtml
@model IEnumerable<Budgetary_App_Final_Edition.Models.Bills>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>